# FHIR Mapping Configuration
# This file externalizes hardcoded FHIR mappings for maintainability

# OMOP domain to FHIR resource type mapping
domain_to_fhir_resource:
  Condition: Condition
  Drug: MedicationRequest
  Measurement: Observation
  Observation: Observation
  Procedure: Procedure
  Device: Device
  Specimen: Specimen
  Visit: Encounter
  Episode: EpisodeOfCare

# Vocabulary to FHIR code system URL mapping
vocabulary_to_fhir_system:
  SNOMED: "http://snomed.info/sct"
  LOINC: "http://loinc.org"
  RxNorm: "http://www.nlm.nih.gov/research/umls/rxnorm"
  ICD10CM: "http://hl7.org/fhir/sid/icd-10-cm"
  ICD10: "http://hl7.org/fhir/sid/icd-10"
  ICD9CM: "http://hl7.org/fhir/sid/icd-9-cm"
  CPT4: "http://www.ama-assn.org/go/cpt"
  HCPCS: "http://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets"
  NDC: "http://hl7.org/fhir/sid/ndc"
  CVX: "http://hl7.org/fhir/sid/cvx"
  ATC: "http://www.whocc.no/atc"
  MeSH: "http://id.nlm.nih.gov/mesh"
  UCUM: "http://unitsofmeasure.org"

# Default vocabulary hints by domain
# Used when searching for concepts
domain_vocabulary_hints:
  Condition:
    - SNOMED
    - ICD10CM
    - ICD10
  Drug:
    - RxNorm
    - RxNorm Extension
    - ATC
  Measurement:
    - LOINC
    - SNOMED
  Observation:
    - SNOMED
    - LOINC
  Procedure:
    - SNOMED
    - CPT4
    - HCPCS
